/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "rgb(var(--primary))",
        "primary-inverse": "rgb(var(--primary-inverse))",
        "primary-hover": "rgb(var(--primary-hover))",
        "primary-active-color": "rgb(var(--primary-active-color))",

        "primary-highlight":
          "rgb(var(--primary)/var(--primary-highlight-opacity))",
        "primary-highlight-inverse": "rgb(var(--primary-highlight-inverse))",
        "primary-highlight-hover":
          "rgb(var(--primary)/var(--primary-highlight-hover-opacity))",

        "primary-50": "rgb(var(--primary-50))",
        "primary-100": "rgb(var(--primary-100))",
        "primary-200": "rgb(var(--primary-200))",
        "primary-300": "rgb(var(--primary-300))",
        "primary-400": "rgb(var(--primary-400))",
        "primary-500": "rgb(var(--primary-500))",
        "primary-600": "rgb(var(--primary-600))",
        "primary-700": "rgb(var(--primary-700))",
        "primary-800": "rgb(var(--primary-800))",
        "primary-900": "rgb(var(--primary-900))",
        "primary-950": "rgb(var(--primary-950))",

        "surface-0": "rgb(var(--surface-0))",
        "surface-50": "rgb(var(--surface-50))",
        "surface-100": "rgb(var(--surface-100))",
        "surface-200": "rgb(var(--surface-200))",
        "surface-300": "rgb(var(--surface-300))",
        "surface-400": "rgb(var(--surface-400))",
        "surface-500": "rgb(var(--surface-500))",
        "surface-600": "rgb(var(--surface-600))",
        "surface-700": "rgb(var(--surface-700))",
        "surface-800": "rgb(var(--surface-800))",
        "surface-900": "rgb(var(--surface-900))",
        "surface-950": "rgb(var(--surface-950))",

        base: "rgba(var(--base))",
        "base-alpha-4": "rgba(var(--base-alpha-4))",
        "base-alpha-12": "rgba(var(--base-alpha-12))",
        "base-alpha-20": "rgba(var(--base-alpha-20))",
        "base-alpha-30": "rgba(var(--base-alpha-30))",
        "base-alpha-58": "rgba(var(--base-alpha-58))",
        "base-light-20": "rgb(var(--base-light-20))",
        "base-dark-20": "rgb(var(--base-dark-20))",
        "red-alpha-8": "rgba(var(--red-alpha-8))",
        "green-alpha-8": "rgba(var(--green-alpha-8))",
        "black-10": "rgb(var(--black-10))",
        "black-40": "rgb(var(--black-40))",
        "black-60": "rgb(var(--black-60))",
        "black-alpha-0": "rgba(var(--black-alpha-0))",
        "black-alpha-1": "rgba(var(--black-alpha-1))",
        "black-alpha-3": "rgba(var(--black-alpha-3))",
        "black-alpha-6": "rgba(var(--black-alpha-6))",
        "black-alpha-10": "rgba(var(--black-alpha-10))",
        "black-alpha-12": "rgba(var(--black-alpha-12))",
        "black-alpha-20": "rgba(var(--black-alpha-20))",
        "black-94": "rgb(var(--black-94))",
        "black-96": "rgb(var(--black-96))",
        "black-98": "rgb(var(--black-98))",
        "white-alpha-6": "rgba(var(--white-alpha-6))",
        "white-alpha-20": "rgba(var(--white-alpha-20))",
        "white-alpha-88": "rgba(var(--white-alpha-88))",
        "white-dark-alpha-78": "rgba(var(--white-dark-alpha-78))",
        "ch-green": "rgb(var(--ch-green))",
        "ch-green-light": "rgb(var(--ch-green-light))",
        "ch-green-dark": "rgb(var(--ch-green-dark))",
        "ch-red": "rgb(var(--ch-red))",
        "ch-red-dark": "rgb(var(--ch-red-dark))",
        "red-dark": "rgb(var(--red-dark))",
        "orange-dark": "rgb(var(--orange-dark))",
        "yellow-dark": "rgb(var(--yellow-dark))",
        "green-dark": "rgb(var(--green-dark))",
        "indigo-dark": "rgb(var(--indigo-dark))",
        "purple-dark": "rgb(var(--purple-dark))",
        "red-light": "rgb(var(--red-light))",
        "orange-light": "rgb(var(--orange-light))",
        "yellow-light": "rgb(var(--yellow-light))",
        "green-light": "rgb(var(--green-light))",
        "indigo-light": "rgb(var(--indigo-light))",
        "purple-light": "rgb(var(--purple-light))",
        "brown-light": "rgb(var(--brown-light))",
        "clay-light": "rgb(var(--clay-light))",
        "lime-light": "rgb(var(--lime-light))",
        "cyan-light": "rgb(var(--cyan-light))",
        "blue-light": "rgb(var(--blue-light))",
        "pink-light": "rgb(var(--pink-light))",

        clay: "rgba(81, 91, 96,1)",
      },

      fontFamily: {
        "tt-firs-text-normal": ["TT Firs Text Normal"],
      },
      boxShadow: {
        sm: "0px 1px 2px 0px #24242408",
        medium: "0px 2px 24px 0px #24242433",
        default: "0px 25px 30px 0px #00000033",
      },
    },
  },
  plugins: [],
};
